# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/projects_2024/Loong_Team/chiplab/chip/soc_demo/nscscc-team/xilinx_ip/axi_clock_converter/axi_clock_converter.xci
# IP: The module: 'axi_clock_converter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/projects_2024/Loong_Team/chiplab/chip/soc_demo/nscscc-team/xilinx_ip/axi_clock_converter/gen/axi_clock_converter_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/projects_2024/Loong_Team/chiplab/chip/soc_demo/nscscc-team/xilinx_ip/axi_clock_converter/gen/axi_clock_converter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/projects_2024/Loong_Team/chiplab/chip/soc_demo/nscscc-team/xilinx_ip/axi_clock_converter/axi_clock_converter.xci
# IP: The module: 'axi_clock_converter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/projects_2024/Loong_Team/chiplab/chip/soc_demo/nscscc-team/xilinx_ip/axi_clock_converter/gen/axi_clock_converter_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/projects_2024/Loong_Team/chiplab/chip/soc_demo/nscscc-team/xilinx_ip/axi_clock_converter/gen/axi_clock_converter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
