# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/projects_2024/Loong_Team/chiplab/chip/soc_demo/nscscc-team/xilinx_ip/axi_ram/axi_ram.xci
# IP: The module: 'axi_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/projects_2024/Loong_Team/chiplab/chip/soc_demo/nscscc-team/xilinx_ip/axi_ram/gen/axi_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/projects_2024/Loong_Team/chiplab/chip/soc_demo/nscscc-team/xilinx_ip/axi_ram/axi_ram.xci
# IP: The module: 'axi_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/projects_2024/Loong_Team/chiplab/chip/soc_demo/nscscc-team/xilinx_ip/axi_ram/gen/axi_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
