# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/projects_2024/Loong_Team/chiplab_try/fpga/nscscc-team/run_vivado/project/loongson.runs/synth_1/soc_axi_lite_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tfbg676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/projects_2024/Loong_Team/chiplab_try/fpga/nscscc-team/run_vivado/project/loongson.cache/wt [current_project]
set_property parent.project_path E:/projects_2024/Loong_Team/chiplab_try/fpga/nscscc-team/run_vivado/project/loongson.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/projects_2024/Loong_Team/chiplab_try/fpga/nscscc-team/run_vivado/project/loongson.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files E:/projects_2024/Loong_Team/chiplab_try/fpga/nscscc-team/software/perf/obj/allbench/axi_ram.coe
add_files E:/projects_2024/Loong_Team/chiplab_try/fpga/nscscc-team/software/func/obj/inst_ram.coe
read_verilog {
  E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/csr.h
  E:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/soc_config.vh
  E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/mycpu.h
}
set_property file_type "Verilog Header" [get_files E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/csr.h]
set_property file_type "Verilog Header" [get_files E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/mycpu.h]
read_verilog -library xil_defaultlib {
  E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/addr_trans.v
  E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/alu.v
  E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/axi_bridge.v
  E:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/axi_wrap/axi_wrap.v
  E:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/ram_wrap/axi_wrap_ram.v
  E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/btb.v
  E:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/CONFREG/confreg.v
  E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/csr.v
  E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/dcache.v
  E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/div.v
  E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/exe_stage.v
  E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/icache.v
  E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/id_stage.v
  E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/if_stage.v
  E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/mem_stage.v
  E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/mul.v
  E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/mycpu_top.v
  E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/perf_counter.v
  E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/regfile.v
  E:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/uart_debug/rst_sync.v
  E:/projects_2024/Loong_Team/chiplab_try/IP/AXI_SRAM_BRIDGE/soc_axi_sram_bridge.v
  E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/tlb_entry.v
  E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/tools.v
  E:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/uart_debug/uart.v
  E:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/uart_debug/uart_debug.v
  E:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/uart_debug/uart_debug_axi.v
  E:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/uart_debug/uart_wrap.v
  E:/projects_2024/Loong_Team/chiplab_try/IP/myCPU/open-la500/wb_stage.v
  E:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/soc_axi_lite_top.v
}
read_ip -quiet E:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/xilinx_ip/axi_ram/axi_ram.xci
set_property used_in_implementation false [get_files -all e:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/xilinx_ip/axi_ram/gen/axi_ram_ooc.xdc]

read_ip -quiet E:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/xilinx_ip/clk_pll/clk_pll.xci
set_property used_in_implementation false [get_files -all e:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/xilinx_ip/clk_pll/gen/clk_pll_board.xdc]
set_property used_in_implementation false [get_files -all e:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/xilinx_ip/clk_pll/gen/clk_pll.xdc]
set_property used_in_implementation false [get_files -all e:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/xilinx_ip/clk_pll/gen/clk_pll_ooc.xdc]

read_ip -quiet E:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/xilinx_ip/axi_crossbar_2x3/axi_crossbar_2x3.xci
set_property used_in_implementation false [get_files -all e:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/xilinx_ip/axi_crossbar_2x3/gen/axi_crossbar_2x3_ooc.xdc]

read_ip -quiet E:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/xilinx_ip/axi_clock_converter/axi_clock_converter.xci
set_property used_in_synthesis false [get_files -all e:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/xilinx_ip/axi_clock_converter/gen/axi_clock_converter_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/xilinx_ip/axi_clock_converter/gen/axi_clock_converter_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/projects_2024/Loong_Team/chiplab_try/chip/soc_demo/nscscc-team/xilinx_ip/axi_clock_converter/gen/axi_clock_converter_ooc.xdc]

read_ip -quiet E:/projects_2024/Loong_Team/open-la500/IP/tagv_sram/tagv_sram.xci
set_property used_in_implementation false [get_files -all e:/projects_2024/Loong_Team/open-la500/IP/tagv_sram/tagv_sram_ooc.xdc]

read_ip -quiet E:/projects_2024/Loong_Team/open-la500/IP/data_bank_sram/data_bank_sram.xci
set_property used_in_implementation false [get_files -all e:/projects_2024/Loong_Team/open-la500/IP/data_bank_sram/data_bank_sram_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/projects_2024/Loong_Team/chiplab_try/fpga/nscscc-team/run_vivado/constraints/soc_lite.xdc
set_property used_in_implementation false [get_files E:/projects_2024/Loong_Team/chiplab_try/fpga/nscscc-team/run_vivado/constraints/soc_lite.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top soc_axi_lite_top -part xc7a200tfbg676-1 -directive PerformanceOptimized -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_axi_lite_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_axi_lite_top_utilization_synth.rpt -pb soc_axi_lite_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
